"""Optional PyTorch helpers for fair combat learning.

Import this subpackage explicitly; the base :mod:`sts_sim` package has no
PyTorch import or runtime dependency.
"""

from .data import (
    DatasetExclusion,
    DatasetManifest,
    RootEntry,
    RootExclusion,
    RootManifest,
    generate_beam_dataset,
    generate_legal_roots,
    load_dataset_manifest,
    load_root_manifest,
)
from .diagnostics import (
    TeacherConflictGroup,
    WinLossScore,
    affine_tanh_win_probability,
    binary_win_loss_calibration,
    calibrate_combat_proxy_win_loss,
    teacher_conflict_report,
)
from .experiment import (
    UNDECLARED_POLICY_REPORT_ONLY,
    UNDECLARED_POLICY_STRICT,
    ArtifactIntegrityError,
    ArtifactIntegrityReport,
    ExperimentPredeclaration,
    ExperimentReproductionError,
    is_mutable_synchronization_path,
    load_experiment_predeclaration,
    normalize_inventory_relative_path,
    reproduce_experiment,
    sync_experiment_wandb,
    verify_artifact_integrity,
    write_artifact_inventory,
    write_scientific_artifact,
)
from .gameplay import (
    RANDOM_CONTRACT,
    PolicyEpisode,
    aggregate_paired_differences,
    aggregate_policy_metrics,
    evaluate_matched_gameplay,
    evaluate_matched_puct_gameplay,
    evaluate_matched_puct_roots,
    evaluate_matched_roots,
    random_policy_index,
    select_greedy_action,
)
from .model import (
    CheckpointSourceMismatchWarning,
    CombatModelConfig,
    FairCombatPolicyValueNet,
    LoadedCheckpoint,
    PolicyValueOutput,
    load_checkpoint,
    policy_value_loss,
    save_checkpoint,
)
from .provenance import RepositoryVersion, capture_repository_version, file_digest
from .puct import (
    network_leaf_evaluator,
    puct_clone_episode_payload,
    puct_search_payload,
    rollout_puct_policy,
    select_puct_action,
)
from .puct_data import generate_puct_dataset
from .records import (
    BatchedTrainingExamples,
    CombatOutcome,
    CounterChange,
    SymbolicCombatDataset,
    SymbolicTrainingRecord,
    TensorizedTrainingExample,
    collate_training_examples,
    fair_observation_digest,
    read_jsonl,
    write_jsonl,
)
from .rewards import COMBAT_PROXY_V1, CombatRewardConfig
from .rollout import (
    CombatRolloutResult,
    RolloutDistribution,
    rollout_model_combat,
    summarize_rollouts,
)
from .tensor import (
    CATEGORY_NAMESPACES,
    FIELD_COVERAGE,
    SCALAR_INDEX,
    SCALAR_NAMES,
    BatchedCombatDecision,
    FrozenVocabulary,
    TensorizedCombatDecision,
    Vocabularies,
    VocabularyBuilder,
    collate_combat_tensors,
    encoder_contract_digest,
    field_coverage_mismatches,
    tensorize_combat,
)
from .training import (
    TrainingConfig,
    TrainingResult,
    evaluate_beam_clone,
    train_beam_clone,
)
from .treatment_control import (
    SHARED_TRAINING_VOCABULARY_KIND,
    SHARED_TRAINING_VOCABULARY_VERSION,
    SharedTrainingVocabulary,
    load_shared_training_vocabulary,
    publish_shared_training_vocabulary,
)

__all__ = [
    "CATEGORY_NAMESPACES",
    "COMBAT_PROXY_V1",
    "FIELD_COVERAGE",
    "RANDOM_CONTRACT",
    "SCALAR_INDEX",
    "SCALAR_NAMES",
    "SHARED_TRAINING_VOCABULARY_KIND",
    "SHARED_TRAINING_VOCABULARY_VERSION",
    "UNDECLARED_POLICY_REPORT_ONLY",
    "UNDECLARED_POLICY_STRICT",
    "ArtifactIntegrityError",
    "ArtifactIntegrityReport",
    "BatchedCombatDecision",
    "BatchedTrainingExamples",
    "CheckpointSourceMismatchWarning",
    "CombatModelConfig",
    "CombatOutcome",
    "CombatRewardConfig",
    "CombatRolloutResult",
    "CounterChange",
    "DatasetExclusion",
    "DatasetManifest",
    "ExperimentPredeclaration",
    "ExperimentReproductionError",
    "FairCombatPolicyValueNet",
    "FrozenVocabulary",
    "LoadedCheckpoint",
    "PolicyEpisode",
    "PolicyValueOutput",
    "RepositoryVersion",
    "RolloutDistribution",
    "RootEntry",
    "RootExclusion",
    "RootManifest",
    "SharedTrainingVocabulary",
    "SymbolicCombatDataset",
    "SymbolicTrainingRecord",
    "TeacherConflictGroup",
    "TensorizedCombatDecision",
    "TensorizedTrainingExample",
    "TrainingConfig",
    "TrainingResult",
    "Vocabularies",
    "VocabularyBuilder",
    "WinLossScore",
    "affine_tanh_win_probability",
    "aggregate_paired_differences",
    "aggregate_policy_metrics",
    "binary_win_loss_calibration",
    "calibrate_combat_proxy_win_loss",
    "capture_repository_version",
    "collate_combat_tensors",
    "collate_training_examples",
    "encoder_contract_digest",
    "evaluate_beam_clone",
    "evaluate_matched_gameplay",
    "evaluate_matched_puct_gameplay",
    "evaluate_matched_puct_roots",
    "evaluate_matched_roots",
    "fair_observation_digest",
    "field_coverage_mismatches",
    "file_digest",
    "generate_beam_dataset",
    "generate_legal_roots",
    "generate_puct_dataset",
    "is_mutable_synchronization_path",
    "load_checkpoint",
    "load_dataset_manifest",
    "load_experiment_predeclaration",
    "load_root_manifest",
    "load_shared_training_vocabulary",
    "network_leaf_evaluator",
    "normalize_inventory_relative_path",
    "policy_value_loss",
    "publish_shared_training_vocabulary",
    "puct_clone_episode_payload",
    "puct_search_payload",
    "random_policy_index",
    "read_jsonl",
    "reproduce_experiment",
    "rollout_model_combat",
    "rollout_puct_policy",
    "save_checkpoint",
    "select_greedy_action",
    "select_puct_action",
    "summarize_rollouts",
    "sync_experiment_wandb",
    "teacher_conflict_report",
    "tensorize_combat",
    "train_beam_clone",
    "verify_artifact_integrity",
    "write_artifact_inventory",
    "write_jsonl",
    "write_scientific_artifact",
]
