"""Optional PyTorch helpers for fair combat learning.

Import this subpackage explicitly; the base :mod:`sts_sim` package has no
PyTorch import or runtime dependency.
"""

from .data import (
    DatasetExclusion,
    DatasetManifest,
    RootEntry,
    RootExclusion,
    RootManifest,
    generate_beam_dataset,
    generate_legal_roots,
    load_dataset_manifest,
    load_root_manifest,
)
from .diagnostics import TeacherConflictGroup, teacher_conflict_report
from .gameplay import (
    RANDOM_CONTRACT,
    PolicyEpisode,
    aggregate_paired_differences,
    aggregate_policy_metrics,
    evaluate_matched_gameplay,
    evaluate_matched_roots,
    random_policy_index,
    select_greedy_action,
)
from .model import (
    CheckpointSourceMismatchWarning,
    CombatModelConfig,
    FairCombatPolicyValueNet,
    LoadedCheckpoint,
    PolicyValueOutput,
    load_checkpoint,
    policy_value_loss,
    save_checkpoint,
)
from .provenance import RepositoryVersion, capture_repository_version, file_digest
from .records import (
    BatchedTrainingExamples,
    CombatOutcome,
    CounterChange,
    SymbolicCombatDataset,
    SymbolicTrainingRecord,
    TensorizedTrainingExample,
    collate_training_examples,
    fair_observation_digest,
    read_jsonl,
    write_jsonl,
)
from .rewards import COMBAT_PROXY_V1, CombatRewardConfig
from .rollout import (
    CombatRolloutResult,
    RolloutDistribution,
    rollout_model_combat,
    summarize_rollouts,
)
from .tensor import (
    CATEGORY_NAMESPACES,
    FIELD_COVERAGE,
    SCALAR_INDEX,
    SCALAR_NAMES,
    BatchedCombatDecision,
    FrozenVocabulary,
    TensorizedCombatDecision,
    Vocabularies,
    VocabularyBuilder,
    collate_combat_tensors,
    encoder_contract_digest,
    field_coverage_mismatches,
    tensorize_combat,
)
from .training import (
    TrainingConfig,
    TrainingResult,
    evaluate_beam_clone,
    train_beam_clone,
)

__all__ = [
    "CATEGORY_NAMESPACES",
    "COMBAT_PROXY_V1",
    "FIELD_COVERAGE",
    "RANDOM_CONTRACT",
    "SCALAR_INDEX",
    "SCALAR_NAMES",
    "BatchedCombatDecision",
    "BatchedTrainingExamples",
    "CheckpointSourceMismatchWarning",
    "CombatModelConfig",
    "CombatOutcome",
    "CombatRewardConfig",
    "CombatRolloutResult",
    "CounterChange",
    "DatasetExclusion",
    "DatasetManifest",
    "FairCombatPolicyValueNet",
    "FrozenVocabulary",
    "LoadedCheckpoint",
    "PolicyEpisode",
    "PolicyValueOutput",
    "RepositoryVersion",
    "RolloutDistribution",
    "RootEntry",
    "RootExclusion",
    "RootManifest",
    "SymbolicCombatDataset",
    "SymbolicTrainingRecord",
    "TeacherConflictGroup",
    "TensorizedCombatDecision",
    "TensorizedTrainingExample",
    "TrainingConfig",
    "TrainingResult",
    "Vocabularies",
    "VocabularyBuilder",
    "aggregate_paired_differences",
    "aggregate_policy_metrics",
    "capture_repository_version",
    "collate_combat_tensors",
    "collate_training_examples",
    "encoder_contract_digest",
    "evaluate_beam_clone",
    "evaluate_matched_gameplay",
    "evaluate_matched_roots",
    "fair_observation_digest",
    "field_coverage_mismatches",
    "file_digest",
    "generate_beam_dataset",
    "generate_legal_roots",
    "load_checkpoint",
    "load_dataset_manifest",
    "load_root_manifest",
    "policy_value_loss",
    "random_policy_index",
    "read_jsonl",
    "rollout_model_combat",
    "save_checkpoint",
    "select_greedy_action",
    "summarize_rollouts",
    "teacher_conflict_report",
    "tensorize_combat",
    "train_beam_clone",
    "write_jsonl",
]
