//! Simulation-only environmental inputs, never real-game trace repair.
//! Source: desktop 12-18-2022 ShopScreen.purchaseCard ->
//! AbstractDungeon.getCardFromPool(rarity, type, false) ->
//! CardGroup.getRandomCard(type, false) -> MathUtils.random(size - 1).

use sts_core::adapter_internals::{
    apply_shop_action,
    content::{
        cards::{ANGER_ID, COMBUST_ID, HAVOC_ID},
        shop_pool::{class_card_pool_of_type_and_rarity_with_fallback, roll_card_rarity_shop},
    },
    generate_shop_screen,
    rng::{ExternalRngInput, ExternalRngKind, MathUtilsRngState, StsRng, TrainingExternalRng},
    CardType, ContentId, Relic, RunAction, RunPhase, RunState, SimError,
};

fn courier_shop(card: ContentId) -> RunState {
    let mut run = RunState::seeded_ironclad(7, 0);
    run.phase = RunPhase::Shop;
    run.event = None;
    run.gold = 999_999;
    run.relics.push(Relic::TheCourier);
    run.shop = Some(generate_shop_screen(&mut run).expect("shop generates"));
    run.shop_merchant_open = true;
    let offer = &mut run.shop.as_mut().expect("shop").cards[0];
    offer.card.content_id = card;
    offer.price = 0;
    run
}

#[test]
fn seeded_math_utils_matches_actual_desktop_jar_vectors() {
    // Generated by new RandomXS128(seed); MathUtils.random = rng; then
    // MathUtils.random(bound), using the actual desktop JAR (not another simulator).
    let bounds = [0, 5, 13, 16, 65_535, 2_147_483_646];
    for (seed, initial, results, final_state) in [
        (
            0,
            (0x8f78_0810_af31_a493, 0xd1f9_a22a_f8e8_3383),
            [0, 4, 8, 3, 45_183, 160_942_672],
            (0xfee6_0553_2384_44e4, 0xf350_75eb_0b3e_593c),
        ),
        (
            1,
            (0xb456_bcfc_34c2_cb2c, 0x7d6e_4ac3_8b2b_1be2),
            [0, 1, 4, 4, 16_137, 1_146_450_529],
            (0xc80f_009c_d532_dbfd, 0x0b86_d464_0c4c_5ec2),
        ),
        (
            u64::MAX,
            (0x64b5_720b_4b82_5f21, 0xfa60_5f44_aea3_667d),
            [0, 4, 13, 5, 22_701, 260_218_937],
            (0x9bbb_62d6_a3d5_f4db, 0xa2a4_4eaf_fe6f_e889),
        ),
        (
            123_456_789,
            (0x8f7c_2920_6384_f886, 0x424f_1c26_6a80_dc24),
            [0, 5, 10, 15, 38_715, 792_540_702],
            (0xe18c_d4e7_b22b_132a, 0x0474_4dbd_e04d_13c5),
        ),
    ] {
        let mut rng = MathUtilsRngState::seeded(seed);
        assert_eq!((rng.state0, rng.state1), initial);
        for (bound, result) in bounds.into_iter().zip(results) {
            assert_eq!(rng.random_int(bound), result);
        }
        assert_eq!((rng.state0, rng.state1), final_state);
    }
}

#[test]
fn training_courier_matches_typed_inputs_for_all_card_types_and_repeated_purchases() {
    for (card, card_type) in [
        (ANGER_ID, CardType::Attack),
        (HAVOC_ID, CardType::Skill),
        (COMBUST_ID, CardType::Power),
    ] {
        for seed in 0..256 {
            let mut training = courier_shop(card);
            training.training_external_rng = Some(TrainingExternalRng::seeded(seed));
            let mut strict = training.clone();
            strict.training_external_rng = None;
            let mut environmental = MathUtilsRngState::seeded(seed);
            for _ in 0..4 {
                let mut rarity_rng =
                    StsRng::with_counter(strict.reward_rng_seed as i64, strict.card_rng_counter);
                let rarity = roll_card_rarity_shop(&mut rarity_rng, strict.card_rarity_factor);
                let pool = class_card_pool_of_type_and_rarity_with_fallback(card_type, rarity);
                let range_inclusive = u32::try_from(pool.len() - 1).expect("small pool");
                strict.pending_external_rng.push(ExternalRngInput {
                    kind: ExternalRngKind::CardGroupGetRandomCardByType,
                    state: environmental,
                    range_inclusive,
                });
                let _ = environmental.random_int(range_inclusive);
                let action = RunAction::BuyShopCard { slot: 0 };
                let restored: RunState =
                    serde_json::from_str(&serde_json::to_string(&training).expect("snapshot"))
                        .expect("restore");
                let next = apply_shop_action(&training, action).expect("training purchase");
                assert_eq!(
                    next,
                    apply_shop_action(&restored, action).expect("restored purchase")
                );
                strict = apply_shop_action(&strict, action).expect("typed-input purchase");
                training = next;
                let mut comparable = training.clone();
                comparable.training_external_rng = None;
                // This includes identities, prices, all run RNG counters, gold,
                // physical card ownership and the rest of the complete run state.
                assert_eq!(comparable, strict);
                training.validate().expect("valid training run");
            }
        }
    }
}

#[test]
fn training_provider_is_not_used_by_colorless_restock_or_queries() {
    let mut training = courier_shop(HAVOC_ID);
    training.training_external_rng = Some(TrainingExternalRng::seeded(42));
    let before = training.clone();
    let _ = sts_core::adapter_internals::legal_run_decision_actions(&training).expect("actions");
    let _ = serde_json::to_string(&training).expect("snapshot");
    assert_eq!(training, before);
    let after = apply_shop_action(&training, RunAction::BuyShopCard { slot: 5 })
        .expect("colorless purchase");
    assert_eq!(after.training_external_rng, before.training_external_rng);
}

#[test]
fn strict_default_and_mixed_input_rejections_are_atomic() {
    let mut run = courier_shop(HAVOC_ID);
    let before = run.clone();
    let action = RunAction::BuyShopCard { slot: 0 };
    assert_eq!(
        apply_shop_action(&run, action),
        Err(SimError::MissingExternalRng(
            "courier_colored_card_selection"
        ))
    );
    assert_eq!(run, before);
    let snapshot = serde_json::to_string(&run).expect("strict snapshot");
    assert!(!snapshot.contains("training_external_rng"));
    let restored: RunState = serde_json::from_str(&snapshot).expect("old snapshot");
    assert!(restored.training_external_rng.is_none());
    run.training_external_rng = Some(TrainingExternalRng::seeded(1));
    run.pending_external_rng.push(ExternalRngInput {
        kind: ExternalRngKind::CardGroupGetRandomCardByType,
        state: MathUtilsRngState::seeded(2),
        range_inclusive: 5,
    });
    let before = run.clone();
    assert!(apply_shop_action(&run, action).is_err());
    assert_eq!(run, before);
    assert!(run.validate().is_err());
}
