// Generated by simulator/tools/build_reward_card_metadata.py from PC 12-18-2022.
// JAR SHA256: cfad868ac8d65a88e71a0bf096fb09f78811e553effe0787c5309a655e081673
// Independent audit data for tests only. No gameplay values come from this table.
use sts_core::card::{CardRarity, CardType};

#[derive(Debug, Clone, Copy)]
pub struct RewardCardMetadata {
    pub key: &'static str,
    pub card_id: &'static str,
    pub cost: i8,
    pub upgraded_cost: i8,
    pub card_type: CardType,
    pub rarity: CardRarity,
}

pub const REWARD_ONLY_CARD_METADATA: &[RewardCardMetadata] = &[
    // com/megacrit/cardcrawl/cards/green/Acrobatics.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ACROBATICS",
        card_id: "Acrobatics",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/BallLightning.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BALL_LIGHTNING",
        card_id: "Ball Lightning",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/Barrage.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BARRAGE",
        card_id: "Barrage",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/BladeDance.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BLADE_DANCE",
        card_id: "Blade Dance",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/ColdSnap.java: constructor; upgrade().
    RewardCardMetadata {
        key: "COLD_SNAP",
        card_id: "Cold Snap",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/purple/Consecrate.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CONSECRATE",
        card_id: "Consecrate",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/purple/CutThroughFate.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CUT_THROUGH_FATE",
        card_id: "CutThroughFate",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/DaggerThrow.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DAGGER_THROW",
        card_id: "Dagger Throw",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/Deflect.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DEFLECT",
        card_id: "Deflect",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/DodgeAndRoll.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DODGE_AND_ROLL",
        card_id: "Dodge and Roll",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/purple/EmptyFist.java: constructor; upgrade().
    RewardCardMetadata {
        key: "EMPTY_FIST",
        card_id: "EmptyFist",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/FlyingKnee.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FLYING_KNEE",
        card_id: "Flying Knee",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/Claw.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CLAW",
        card_id: "Gash",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/Outmaneuver.java: constructor; upgrade().
    RewardCardMetadata {
        key: "OUTMANEUVER",
        card_id: "Outmaneuver",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/PiercingWail.java: constructor; upgrade().
    RewardCardMetadata {
        key: "PIERCING_WAIL",
        card_id: "PiercingWail",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/Rebound.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REBOUND",
        card_id: "Rebound",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/purple/SashWhip.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SASH_WHIP",
        card_id: "SashWhip",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/Stack.java: constructor; upgrade().
    RewardCardMetadata {
        key: "STACK",
        card_id: "Stack",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/SuckerPunch.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SUCKER_PUNCH",
        card_id: "Sucker Punch",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/blue/Turbo.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TURBO",
        card_id: "Turbo",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Common,
    },
    // com/megacrit/cardcrawl/cards/green/Accuracy.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ACCURACY",
        card_id: "Accuracy",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Rushdown.java: constructor; upgrade().
    RewardCardMetadata {
        key: "RUSHDOWN",
        card_id: "Adaptation",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Aggregate.java: constructor; upgrade().
    RewardCardMetadata {
        key: "AGGREGATE",
        card_id: "Aggregate",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/AllOutAttack.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ALL_OUT_ATTACK",
        card_id: "All Out Attack",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/AutoShields.java: constructor; upgrade().
    RewardCardMetadata {
        key: "AUTO_SHIELDS",
        card_id: "Auto Shields",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Backstab.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BACKSTAB",
        card_id: "Backstab",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/BattleHymn.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BATTLE_HYMN",
        card_id: "BattleHymn",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Blizzard.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BLIZZARD",
        card_id: "Blizzard",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Blur.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BLUR",
        card_id: "Blur",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/BouncingFlask.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BOUNCING_FLASK",
        card_id: "Bouncing Flask",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/CalculatedGamble.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CALCULATED_GAMBLE",
        card_id: "Calculated Gamble",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/CarveReality.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CARVE_REALITY",
        card_id: "CarveReality",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Catalyst.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CATALYST",
        card_id: "Catalyst",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Chaos.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CHAOS",
        card_id: "Chaos",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Chill.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CHILL",
        card_id: "Chill",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Choke.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CHOKE",
        card_id: "Choke",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Collect.java: constructor; upgrade().
    RewardCardMetadata {
        key: "COLLECT",
        card_id: "Collect",
        cost: -1,
        upgraded_cost: -1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Concentrate.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CONCENTRATE",
        card_id: "Concentrate",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Consume.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CONSUME",
        card_id: "Consume",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Dash.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DASH",
        card_id: "Dash",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/DeceiveReality.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DECEIVE_REALITY",
        card_id: "DeceiveReality",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Defragment.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DEFRAGMENT",
        card_id: "Defragment",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Distraction.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DISTRACTION",
        card_id: "Distraction",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/DoomAndGloom.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DOOM_AND_GLOOM",
        card_id: "Doom and Gloom",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/DoubleEnergy.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DOUBLE_ENERGY",
        card_id: "Double Energy",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/EndlessAgony.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ENDLESS_AGONY",
        card_id: "Endless Agony",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/EscapePlan.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ESCAPE_PLAN",
        card_id: "Escape Plan",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Expertise.java: constructor; upgrade().
    RewardCardMetadata {
        key: "EXPERTISE",
        card_id: "Expertise",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/FTL.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FTL",
        card_id: "FTL",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Finisher.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FINISHER",
        card_id: "Finisher",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Flechettes.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FLECHETTES",
        card_id: "Flechettes",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Footwork.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FOOTWORK",
        card_id: "Footwork",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/ForceField.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FORCE_FIELD",
        card_id: "Force Field",
        cost: 4,
        upgraded_cost: 4,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/ForeignInfluence.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FOREIGN_INFLUENCE",
        card_id: "ForeignInfluence",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Fusion.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FUSION",
        card_id: "Fusion",
        cost: 2,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/GeneticAlgorithm.java: constructor; upgrade().
    RewardCardMetadata {
        key: "GENETIC_ALGORITHM",
        card_id: "Genetic Algorithm",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Glacier.java: constructor; upgrade().
    RewardCardMetadata {
        key: "GLACIER",
        card_id: "Glacier",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Heatsinks.java: constructor; upgrade().
    RewardCardMetadata {
        key: "HEATSINKS",
        card_id: "Heatsinks",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/HeelHook.java: constructor; upgrade().
    RewardCardMetadata {
        key: "HEEL_HOOK",
        card_id: "Heel Hook",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/HelloWorld.java: constructor; upgrade().
    RewardCardMetadata {
        key: "HELLO_WORLD",
        card_id: "Hello World",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Indignation.java: constructor; upgrade().
    RewardCardMetadata {
        key: "INDIGNATION",
        card_id: "Indignation",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/InfiniteBlades.java: constructor; upgrade().
    RewardCardMetadata {
        key: "INFINITE_BLADES",
        card_id: "Infinite Blades",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/InnerPeace.java: constructor; upgrade().
    RewardCardMetadata {
        key: "INNER_PEACE",
        card_id: "InnerPeace",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/LockOn.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BULLSEYE",
        card_id: "Lockon",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Loop.java: constructor; upgrade().
    RewardCardMetadata {
        key: "LOOP",
        card_id: "Loop",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/MasterfulStab.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MASTERFUL_STAB",
        card_id: "Masterful Stab",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Meditate.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MEDITATE",
        card_id: "Meditate",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Melter.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MELTER",
        card_id: "Melter",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/MentalFortress.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MENTAL_FORTRESS",
        card_id: "MentalFortress",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/NoxiousFumes.java: constructor; upgrade().
    RewardCardMetadata {
        key: "NOXIOUS_FUMES",
        card_id: "Noxious Fumes",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Perseverance.java: constructor; upgrade().
    RewardCardMetadata {
        key: "PERSEVERANCE",
        card_id: "Perseverance",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Predator.java: constructor; upgrade().
    RewardCardMetadata {
        key: "PREDATOR",
        card_id: "Predator",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/ReachHeaven.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REACH_HEAVEN",
        card_id: "ReachHeaven",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Reflex.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REFLEX",
        card_id: "Reflex",
        cost: -2,
        upgraded_cost: -2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/ReinforcedBody.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REINFORCED_BODY",
        card_id: "Reinforced Body",
        cost: -1,
        upgraded_cost: -1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Reprogram.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REPROGRAM",
        card_id: "Reprogram",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/RiddleWithHoles.java: constructor; upgrade().
    RewardCardMetadata {
        key: "RIDDLE_WITH_HOLES",
        card_id: "Riddle With Holes",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Sanctity.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SANCTITY",
        card_id: "Sanctity",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/SelfRepair.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SELF_REPAIR",
        card_id: "Self Repair",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Setup.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SETUP",
        card_id: "Setup",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/SignatureMove.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SIGNATURE_MOVE",
        card_id: "SignatureMove",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Overclock.java: constructor; upgrade().
    RewardCardMetadata {
        key: "OVERCLOCK",
        card_id: "Steam Power",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Study.java: constructor; upgrade().
    RewardCardMetadata {
        key: "STUDY",
        card_id: "Study",
        cost: 2,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Sunder.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SUNDER",
        card_id: "Sunder",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Swivel.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SWIVEL",
        card_id: "Swivel",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Tactician.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TACTICIAN",
        card_id: "Tactician",
        cost: -2,
        upgraded_cost: -2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/TalkToTheHand.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TALK_TO_THE_HAND",
        card_id: "TalkToTheHand",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Tantrum.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TANTRUM",
        card_id: "Tantrum",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/Tempest.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TEMPEST",
        card_id: "Tempest",
        cost: -1,
        upgraded_cost: -1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/Terror.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TERROR",
        card_id: "Terror",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/SimmeringFury.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SIMMERING_FURY",
        card_id: "Vengeance",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/WaveOfTheHand.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WAVE_OF_THE_HAND",
        card_id: "WaveOfTheHand",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Weave.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WEAVE",
        card_id: "Weave",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/WellLaidPlans.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WELL_LAID_PLANS",
        card_id: "Well Laid Plans",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/WheelKick.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WHEEL_KICK",
        card_id: "WheelKick",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/blue/WhiteNoise.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WHITE_NOISE",
        card_id: "White Noise",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Foresight.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FORESIGHT",
        card_id: "Wireheading",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/Worship.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WORSHIP",
        card_id: "Worship",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/purple/WreathOfFlame.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WREATH_OF_FLAME",
        card_id: "WreathOfFlame",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Uncommon,
    },
    // com/megacrit/cardcrawl/cards/green/AThousandCuts.java: constructor; upgrade().
    RewardCardMetadata {
        key: "A_THOUSAND_CUTS",
        card_id: "A Thousand Cuts",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/Adrenaline.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ADRENALINE",
        card_id: "Adrenaline",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/AllForOne.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ALL_FOR_ONE",
        card_id: "All For One",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Alpha.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ALPHA",
        card_id: "Alpha",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Amplify.java: constructor; upgrade().
    RewardCardMetadata {
        key: "AMPLIFY",
        card_id: "Amplify",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Brilliance.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BRILLIANCE",
        card_id: "Brilliance",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Buffer.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BUFFER",
        card_id: "Buffer",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/BulletTime.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BULLET_TIME",
        card_id: "Bullet Time",
        cost: 3,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/Burst.java: constructor; upgrade().
    RewardCardMetadata {
        key: "BURST",
        card_id: "Burst",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/ConjureBlade.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CONJURE_BLADE",
        card_id: "ConjureBlade",
        cost: -1,
        upgraded_cost: -1,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/CoreSurge.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CORE_SURGE",
        card_id: "Core Surge",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/CorpseExplosion.java: constructor; upgrade().
    RewardCardMetadata {
        key: "CORPSE_EXPLOSION",
        card_id: "Corpse Explosion",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/DeusExMachina.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DEUS_EX_MACHINA",
        card_id: "DeusExMachina",
        cost: -2,
        upgraded_cost: -2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/DevaForm.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DEVA_FORM",
        card_id: "DevaForm",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Devotion.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DEVOTION",
        card_id: "Devotion",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/DieDieDie.java: constructor; upgrade().
    RewardCardMetadata {
        key: "DIE_DIE_DIE",
        card_id: "Die Die Die",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/EchoForm.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ECHO_FORM",
        card_id: "Echo Form",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Electrodynamics.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ELECTRODYNAMICS",
        card_id: "Electrodynamics",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/Envenom.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ENVENOM",
        card_id: "Envenom",
        cost: 2,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Establishment.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ESTABLISHMENT",
        card_id: "Establishment",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Fission.java: constructor; upgrade().
    RewardCardMetadata {
        key: "FISSION",
        card_id: "Fission",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/GlassKnife.java: constructor; upgrade().
    RewardCardMetadata {
        key: "GLASS_KNIFE",
        card_id: "Glass Knife",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/GrandFinale.java: constructor; upgrade().
    RewardCardMetadata {
        key: "GRAND_FINALE",
        card_id: "Grand Finale",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Hyperbeam.java: constructor; upgrade().
    RewardCardMetadata {
        key: "HYPERBEAM",
        card_id: "Hyperbeam",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/MachineLearning.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MACHINE_LEARNING",
        card_id: "Machine Learning",
        cost: 1,
        upgraded_cost: 1,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/MasterReality.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MASTER_REALITY",
        card_id: "MasterReality",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/MeteorStrike.java: constructor; upgrade().
    RewardCardMetadata {
        key: "METEOR_STRIKE",
        card_id: "Meteor Strike",
        cost: 5,
        upgraded_cost: 5,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/MultiCast.java: constructor; upgrade().
    RewardCardMetadata {
        key: "MULTI_CAST",
        card_id: "Multi-Cast",
        cost: -1,
        upgraded_cost: -1,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/Nightmare.java: constructor; upgrade().
    RewardCardMetadata {
        key: "NIGHTMARE",
        card_id: "Night Terror",
        cost: 3,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Omniscience.java: constructor; upgrade().
    RewardCardMetadata {
        key: "OMNISCIENCE",
        card_id: "Omniscience",
        cost: 4,
        upgraded_cost: 3,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/PhantasmalKiller.java: constructor; upgrade().
    RewardCardMetadata {
        key: "PHANTASMAL_KILLER",
        card_id: "Phantasmal Killer",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Ragnarok.java: constructor; upgrade().
    RewardCardMetadata {
        key: "RAGNAROK",
        card_id: "Ragnarok",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Rainbow.java: constructor; upgrade().
    RewardCardMetadata {
        key: "RAINBOW",
        card_id: "Rainbow",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Reboot.java: constructor; upgrade().
    RewardCardMetadata {
        key: "REBOOT",
        card_id: "Reboot",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Scrawl.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SCRAWL",
        card_id: "Scrawl",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/Seek.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SEEK",
        card_id: "Seek",
        cost: 0,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/SpiritShield.java: constructor; upgrade().
    RewardCardMetadata {
        key: "SPIRIT_SHIELD",
        card_id: "SpiritShield",
        cost: 2,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/blue/ThunderStrike.java: constructor; upgrade().
    RewardCardMetadata {
        key: "THUNDER_STRIKE",
        card_id: "Thunder Strike",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Attack,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/ToolsOfTheTrade.java: constructor; upgrade().
    RewardCardMetadata {
        key: "TOOLS_OF_THE_TRADE",
        card_id: "Tools of the Trade",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Vault.java: constructor; upgrade().
    RewardCardMetadata {
        key: "VAULT",
        card_id: "Vault",
        cost: 3,
        upgraded_cost: 2,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/Alchemize.java: constructor; upgrade().
    RewardCardMetadata {
        key: "ALCHEMIZE",
        card_id: "Venomology",
        cost: 1,
        upgraded_cost: 0,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/purple/Wish.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WISH",
        card_id: "Wish",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Skill,
        rarity: CardRarity::Rare,
    },
    // com/megacrit/cardcrawl/cards/green/WraithForm.java: constructor; upgrade().
    RewardCardMetadata {
        key: "WRAITH_FORM",
        card_id: "Wraith Form v2",
        cost: 3,
        upgraded_cost: 3,
        card_type: CardType::Power,
        rarity: CardRarity::Rare,
    },
];
