"""Typed Python API for the Slay the Spire simulator.

The fair combat API is the default public surface. The ``Omni*`` classes are
explicitly privileged debugging and search tools retained for existing users.
"""

from ._native import (
    DebugTransition,
    DecisionUnavailableError,
    ExactCombatAction,
    ExactRunAction,
    ExactRunStepResult,
    ExactStepResult,
    InvalidAuthoritativeStateError,
    InvalidChoiceError,
    NoActiveCombatError,
    NotInCombatError,
    OmniCombatEnv,
    OmniRunEnv,
    RustSearchRecommendation,
    StaleDecisionError,
    UnknownPublicContentError,
    slaythedata_preflight_json,
    sts_seed_long_to_string,
)
from .fair import (
    DecisionRevision,
    FairCard,
    FairCardDynamicValues,
    FairCombatEnv,
    FairCombatObservation,
    FairCombatPhase,
    FairContext,
    FairCounter,
    FairDecision,
    FairHandCard,
    FairIntentCategory,
    FairMonster,
    FairMonsterIntent,
    FairPile,
    FairPlayer,
    FairPotionSlot,
    FairPower,
    FairRelic,
    FairSelection,
    FairSelectionKind,
    FairSelectionOption,
    FairStepResult,
    PlayerChoice,
    PlayerChoiceKind,
    PlayerChoiceRequest,
)

__all__ = [
    "DebugTransition",
    "DecisionRevision",
    "DecisionUnavailableError",
    "ExactCombatAction",
    "ExactRunAction",
    "ExactRunStepResult",
    "ExactStepResult",
    "FairCard",
    "FairCardDynamicValues",
    "FairCombatEnv",
    "FairCombatObservation",
    "FairCombatPhase",
    "FairContext",
    "FairCounter",
    "FairDecision",
    "FairHandCard",
    "FairIntentCategory",
    "FairMonster",
    "FairMonsterIntent",
    "FairPile",
    "FairPlayer",
    "FairPotionSlot",
    "FairPower",
    "FairRelic",
    "FairSelection",
    "FairSelectionKind",
    "FairSelectionOption",
    "FairStepResult",
    "InvalidAuthoritativeStateError",
    "InvalidChoiceError",
    "NoActiveCombatError",
    "NotInCombatError",
    "OmniCombatEnv",
    "OmniRunEnv",
    "PlayerChoice",
    "PlayerChoiceKind",
    "PlayerChoiceRequest",
    "RustSearchRecommendation",
    "StaleDecisionError",
    "UnknownPublicContentError",
    "slaythedata_preflight_json",
    "sts_seed_long_to_string",
]
