class NoActiveCombatError(ValueError): ...
class InvalidAuthoritativeStateError(ValueError): ...
class UnknownPublicContentError(ValueError): ...
class NotInCombatError(ValueError): ...
class DecisionUnavailableError(ValueError): ...
class StaleDecisionError(ValueError): ...
class InvalidChoiceError(ValueError): ...

class Action:
    def revision(self) -> int: ...
    def family(self) -> str: ...
    def kind(self) -> str: ...
    def public_choice_json(self) -> str | None: ...
    def public_action_json(self) -> str: ...

class DebugTransition:
    action_json: str
    previous_hash: str
    resulting_hash: str
    events_json: str
    rng_draws_json: str
    simulator_error: str | None

class ExactCombatAction:
    @staticmethod
    def end_turn() -> ExactCombatAction: ...
    @staticmethod
    def play_card(card_id: int, target: int | None) -> ExactCombatAction: ...
    def json(self) -> str: ...
    def kind(self) -> str: ...
    def card_id(self) -> int | None: ...
    def target(self) -> int | None: ...

class ExactRunAction:
    @staticmethod
    def skip_reward() -> ExactRunAction: ...
    @staticmethod
    def take_gold_reward() -> ExactRunAction: ...
    @staticmethod
    def open_card_reward() -> ExactRunAction: ...
    def json(self) -> str: ...
    def family(self) -> str: ...
    def kind(self) -> str: ...

class ExactStepResult:
    state_json: str
    snapshot_json: str
    snapshot_hash: str
    phase: str
    exact_legal_actions: list[ExactCombatAction]
    transition: DebugTransition
    terminal: bool
    terminal_reason: str | None

class ExactRunStepResult:
    state_json: str
    snapshot_json: str
    snapshot_hash: str
    phase: str
    current_decision: str
    exact_legal_actions: list[ExactRunAction]
    transition: DebugTransition
    unsupported_reason: str | None

class RustSearchRecommendation:
    best_action: ExactRunAction | None
    principal_variation: list[ExactRunAction]
    value: float
    actions: int
    nodes: int
    terminal_reason: str | None
    final_hp: float
    monster_hp: float

class OmniCombatEnv:
    @staticmethod
    def initial_fixture() -> OmniCombatEnv: ...
    @staticmethod
    def from_state_json_for_debugging(json: str) -> OmniCombatEnv: ...
    @staticmethod
    def from_snapshot_json(json: str) -> OmniCombatEnv: ...
    def clone(self) -> OmniCombatEnv: ...
    def state_json(self) -> str: ...
    def snapshot_json(self) -> str: ...
    def snapshot_hash(self) -> str: ...
    def phase(self) -> str: ...
    def exact_legal_actions(self) -> list[ExactCombatAction]: ...
    def step(self, action: ExactCombatAction) -> ExactStepResult: ...

class OmniRunEnv:
    @staticmethod
    def combat_fixture() -> OmniRunEnv: ...
    @staticmethod
    def map_fixture() -> OmniRunEnv: ...
    @staticmethod
    def new_ironclad(seed: str, ascension: int | None = ...) -> OmniRunEnv: ...
    @staticmethod
    def from_state_json_for_debugging(json: str) -> OmniRunEnv: ...
    @staticmethod
    def from_snapshot_json(json: str) -> OmniRunEnv: ...
    def clone(self) -> OmniRunEnv: ...
    def state_json(self) -> str: ...
    def snapshot_json(self) -> str: ...
    def snapshot_hash(self) -> str: ...
    def revision(self) -> int: ...
    def phase(self) -> str: ...
    def current_decision(self) -> str: ...
    def unsupported_reason(self) -> str | None: ...
    def legal_actions(self) -> list[Action]: ...
    def observation_json(self) -> str: ...
    def debug_add_card(self, key: str) -> None: ...
    def debug_add_relic(self, name: str) -> None: ...
    def debug_add_potion(self, name: str) -> None: ...
    def step_action(self, action: Action) -> None: ...
    def exact_legal_actions(self) -> list[ExactRunAction]: ...
    def step(self, action: ExactRunAction) -> ExactRunStepResult: ...
    def rust_greedy_combat_search(
        self,
        max_actions: int,
        objective: str | None,
        allowed_potions: list[str] | None,
    ) -> RustSearchRecommendation: ...
    def rust_beam_combat_search(
        self,
        max_actions: int,
        objective: str | None,
        allowed_potions: list[str] | None,
        beam_width: int,
    ) -> RustSearchRecommendation: ...

class FairCombatEnv:
    @staticmethod
    def combat_fixture() -> FairCombatEnv: ...
    @staticmethod
    def from_snapshot_for_testing(json: str) -> FairCombatEnv: ...
    def clone(self) -> FairCombatEnv: ...
    def decision_json(self) -> str: ...
    def step_json(self, request_json: str) -> str: ...

def slaythedata_preflight_json(content: str, line_index: int | None = ...) -> str: ...
def sts_seed_long_to_string(seed: int) -> str: ...
def card_keys() -> list[str]: ...
def card_catalogue_json() -> str: ...
def relic_names() -> list[str]: ...
def potion_names() -> list[str]: ...
