class NoActiveCombatError(ValueError): ...
class InvalidAuthoritativeStateError(ValueError): ...
class UnknownPublicContentError(ValueError): ...
class UnmodeledPublicContentError(ValueError): ...
class NotInCombatError(ValueError): ...
class DecisionUnavailableError(ValueError): ...
class StaleDecisionError(ValueError): ...
class InvalidChoiceError(ValueError): ...

class Action:
    def revision(self) -> int: ...
    def family(self) -> str: ...
    def kind(self) -> str: ...
    def public_choice_json(self) -> str | None: ...
    def public_action_json(self) -> str: ...

class OmniRunEnv:
    @staticmethod
    def combat_fixture() -> OmniRunEnv: ...
    @staticmethod
    def map_fixture() -> OmniRunEnv: ...
    @staticmethod
    def new_ironclad(seed: str, ascension: int | None = ...) -> OmniRunEnv: ...
    @staticmethod
    def from_snapshot_json(json: str) -> OmniRunEnv: ...
    def clone(self) -> OmniRunEnv: ...
    def state_json(self) -> str: ...
    def snapshot_json(self) -> str: ...
    def snapshot_hash(self) -> str: ...
    def revision(self) -> int: ...
    def phase(self) -> str: ...
    def current_decision(self) -> str: ...
    def unsupported_reason(self) -> str | None: ...
    def legal_actions(self) -> list[Action]: ...
    def observation_json(self) -> str: ...
    def debug_add_card(self, key: str) -> None: ...
    def debug_add_relic(self, name: str) -> None: ...
    def debug_add_potion(self, name: str) -> None: ...
    def step_action(self, action: Action) -> str | None: ...
    def step_action_json(self, action: Action) -> str: ...
    def beam_clone_episode_json(
        self,
        depth: int = ...,
        width: int = ...,
        transition_budget: int = ...,
        max_decisions: int = ...,
        max_player_turns: int = ...,
        deduplicate_search_states: bool = ...,
    ) -> str: ...
    def puct_search_json(
        self,
        evaluator: object,
        c_puct: float = ...,
        simulation_budget: int = ...,
        transition_budget: int = ...,
        reward_config_json: str | None = ...,
        episode_root_max_hp: int | None = ...,
        episode_root_gold: int | None = ...,
        leaf_cache: str | None = ...,
    ) -> str: ...
    def puct_clone_episode_json(
        self,
        evaluator: object,
        c_puct: float = ...,
        simulation_budget: int = ...,
        transition_budget: int = ...,
        max_decisions: int = ...,
        max_player_turns: int = ...,
        reward_config_json: str | None = ...,
        leaf_cache: str | None = ...,
    ) -> str: ...

def sts_seed_long_to_string(seed: int) -> str: ...
def card_keys() -> list[str]: ...
def card_catalogue_json() -> str: ...
def combat_player_choice_kinds() -> list[str]: ...
def relic_names() -> list[str]: ...
def potion_names() -> list[str]: ...
