"""Generate reward-only foreign-card metadata from the authoritative desktop JAR.

Requires CFR-decompiled cards/{blue,green,purple} from that same JAR. This does
not implement card effects, modify pools, or manufacture gameplay parity. The
output remains separate from the gameplay CardDefinition registry.

uv run --no-project python simulator/tools/build_reward_card_metadata.py \
    --jar /path/to/desktop-1.0.jar --source /path/to/cfr-output \
    --out simulator/crates/sts_core/src/content/reward_card_metadata.rs
"""

import argparse
import hashlib
import json
import re
import zipfile
from pathlib import Path

TARGET_SHA256 = "cfad868ac8d65a88e71a0bf096fb09f78811e553effe0787c5309a655e081673"


def normalized(value):
    return re.sub("[^a-z0-9]", "", value.lower())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jar", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    if hashlib.sha256(args.jar.read_bytes()).hexdigest() != TARGET_SHA256:
        parser.error("JAR differs from the audited target")
    root = Path(__file__).resolve().parents[1] / "crates/sts_core/src"
    modeled = {
        normalized(key)
        for key in re.findall(
            r'key:\s*"([^"]+)"', (root / "content/cards.rs").read_text()
        )
    }
    with zipfile.ZipFile(args.jar) as jar:
        localized = json.loads(jar.read("localization/eng/cards.json"))
    identities = {normalized(value["NAME"]): key for key, value in localized.items()}
    classes = {}
    for package in ("blue", "green", "purple"):
        for path in (args.source / "com/megacrit/cardcrawl/cards" / package).glob(
            "*.java"
        ):
            source = path.read_text()
            identity = re.search(r'public static final String ID = "([^"]+)";', source)
            if identity:
                classes[identity[1]] = (path, source)
    rows = []
    pools = (root / "run/reward.rs").read_text()
    for rarity in ("COMMON", "UNCOMMON", "RARE"):
        match = re.search(
            rf"const ANY_COLOR_{rarity}_CARDS:.*?= &\[(.*?)\];", pools, re.DOTALL
        )
        if not match:
            raise ValueError(f"Missing {rarity} pool")
        for key in re.findall(r'"([^"]+)"', match[1]):
            if normalized(key) in modeled:
                continue
            identity = identities[normalized(key)]
            path, source = classes[identity]
            constructor = re.search(
                r'super\(ID, .*?, "[^"]+", (-?\d+), .*?, AbstractCard.CardType\.(\w+), AbstractCard.CardColor\.\w+, AbstractCard.CardRarity\.(\w+), AbstractCard.CardTarget\.\w+\);',
                source,
            )
            if not constructor:
                raise ValueError(f"Cannot parse constructor: {path}")
            cost, kind, actual_rarity = constructor.groups()
            if actual_rarity != rarity or kind not in ("ATTACK", "SKILL", "POWER"):
                raise ValueError(f"Unexpected collectible type/rarity: {path}")
            upgraded = re.findall(r"upgradeBaseCost\((-?\d+)\)", source)
            if len(upgraded) > 1:
                raise ValueError(f"Ambiguous upgraded cost: {path}")
            rows.append(
                (
                    key,
                    identity,
                    int(cost),
                    int(upgraded[0]) if upgraded else int(cost),
                    kind.title(),
                    rarity.title(),
                    str(path.relative_to(args.source)),
                )
            )
    header = (
        """// Generated by simulator/tools/build_reward_card_metadata.py from PC 12-18-2022.
// JAR SHA256: """
        + TARGET_SHA256
        + """
// Reward preview metadata ONLY. No gameplay effects are supplied by this table.
use crate::{card::{CardRarity, CardType}, content::shop_pool::shop_card_content_id, ids::ContentId};

#[derive(Debug, Clone, Copy)]
pub struct RewardCardMetadata {
    pub key: &'static str,
    pub card_id: &'static str,
    pub cost: i8,
    pub upgraded_cost: i8,
    pub card_type: CardType,
    pub rarity: CardRarity,
}

pub const REWARD_ONLY_CARD_METADATA: &[RewardCardMetadata] = &[
"""
    )
    lines = [header]
    for key, identity, cost, upgraded, kind, rarity, source in rows:
        lines.append(f"    // {source}: constructor; upgrade().\n")
        lines.append(
            f"    RewardCardMetadata {{ key: {json.dumps(key)}, card_id: {json.dumps(identity)}, cost: {cost}, upgraded_cost: {upgraded}, card_type: CardType::{kind}, rarity: CardRarity::{rarity} }}, \n"
        )
    lines.append("""];

#[must_use]
pub fn reward_only_card_metadata(id: ContentId) -> Option<&'static RewardCardMetadata> {
    REWARD_ONLY_CARD_METADATA.iter().find(|card| shop_card_content_id(card.key) == id)
}
""")
    args.out.write_text("".join(lines))
    print(f"Generated {len(rows)} reward-only entries; no gameplay definitions added")


if __name__ == "__main__":
    main()
